name: ğŸ“¦ CI/CD


on:
    push:
      branches:
          - master


jobs:
    roundup:
        name: ğŸ¤  Roundup
        runs-on: ubuntu-latest
        steps:
            - 
                name: ğŸ’³ Checking out repository
                uses: actions/checkout@v2
            -
                name: ğŸ„ Rounding it up
                uses: NASA-PDS/roundup-action@master
                with:
                    assembly: 'stable'
                env:
                    ADMIN_GITHUB_TOKEN: ${{secrets.pat}}
                    CODE_SIGNING_KEY:   ${{secrets.CODE_SIGNING_KEY}}
                    ossrh_username:     ${{secrets.OSSRH_USERNAME}}
                    ossrh_password:     ${{secrets.OSSRH_TOKEN}}
